---
# Configuration for Matik DBManager
# This is to be used only for local development via docker-compose.

common:
  environment: ${ENVIRONMENT}
  log_level: ${LOG_LEVEL}

mysql:
  engine: mysql
  endpoint: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  database: ${MYSQL_DATABASE}
  use_iam: false
  ssl_mode: disabled
