"""initial schema

Revision ID: 616f7b7e3e44
Revises:
Create Date: 2026-02-12 01:11:54.778577+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic
revision = "616f7b7e3e44"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ghe_organizations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org"),
        sa.UniqueConstraint("org_id"),
    )
    op.create_table(
        "ghe_pr_tracker",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("cutoff_date", sa.DateTime(), nullable=False),
        sa.Column("prs_crawled_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ghe_pr_tracker_cutoff_date"),
        "ghe_pr_tracker",
        ["cutoff_date"],
        unique=False,
    )
    op.create_table(
        "ghe_pull_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pull_request_id", sa.BigInteger(), nullable=False),
        sa.Column("pull_request_number", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("merged", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("merged_at", sa.DateTime(), nullable=True),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("target_branch_name", sa.String(length=255), nullable=False),
        sa.Column("pull_request_summary", sa.Text(), nullable=True),
        sa.Column("jira_tcmr_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("environment", sa.Text(), nullable=True),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("services", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pull_request_id", "repository_id", name="uq_ghe_pr_repo"),
    )
    op.create_index(
        op.f("ix_ghe_pull_requests_repository_id"),
        "ghe_pull_requests",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "ghe_repositories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "org_id", name="uq_ghe_repo_id_org_id"),
    )
    op.create_index(
        op.f("ix_ghe_repositories_org_id"), "ghe_repositories", ["org_id"], unique=False
    )
    op.create_table(
        "greenroom_entities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("api_version", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=True),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("labels", mysql.JSON(), nullable=True),
        sa.Column("annotations", mysql.JSON(), nullable=True),
        sa.Column("tags", mysql.JSON(), nullable=True),
        sa.Column("spec", mysql.JSON(), nullable=True),
        sa.Column("relations", mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidentio_incidents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("incident_id", sa.String(length=255), nullable=False),
        sa.Column("reference_id", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=255), nullable=False),
        sa.Column("slack_channel_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("visibility", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("declined_at", sa.DateTime(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("impact_started_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("impacted_parties", mysql.JSON(), nullable=True),
        sa.Column("impacted_core_functions", mysql.JSON(), nullable=True),
        sa.Column("core_booking_hosting_flow_impacted", sa.Boolean(), nullable=True),
        sa.Column("affected_services", mysql.JSON(), nullable=True),
        sa.Column("root_cause_service", sa.String(length=255), nullable=True),
        sa.Column("root_cause_change_type", sa.String(length=255), nullable=True),
        sa.Column("root_cause_change_type_other", sa.Text(), nullable=True),
        sa.Column(
            "root_cause_change_type_config", sa.String(length=255), nullable=True
        ),
        sa.Column("environment", sa.String(length=255), nullable=True),
        sa.Column("detection_methods", mysql.JSON(), nullable=True),
        sa.Column("detection_link", sa.Text(), nullable=True),
        sa.Column("root_cause_summary", sa.Text(), nullable=True),
        sa.Column("root_cause_summary_hash", sa.String(length=64), nullable=True),
        sa.Column("status_category", sa.String(length=50), nullable=True),
        sa.Column("description_summary", sa.Text(), nullable=True),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "incident_id", "reference_id", name="uq_incident_reference"
        ),
    )
    op.create_table(
        "incidentio_tracker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("error_message", sa.String(length=3072), nullable=True),
        sa.Column("initial_sync_complete", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at_cursor", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jira_batch_tracker",
        sa.Column("ticket_type", sa.String(length=50), nullable=False),
        sa.Column("batch_start", sa.DateTime(), nullable=False),
        sa.Column("batch_end", sa.DateTime(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("last_processed_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticket_type"),
    )
    op.create_table(
        "jira_issues",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.String(length=255), nullable=False),
        sa.Column("issue_key", sa.String(length=255), nullable=False),
        sa.Column("ticket_type", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("issue_summary", sa.Text(), nullable=True),
        sa.Column("issue_comments_summary", sa.Text(), nullable=True),
        sa.Column("summary_hash", sa.String(length=64), nullable=True),
        sa.Column("comments_hash", sa.String(length=64), nullable=True),
        sa.Column("tcmr_related_git_pr_link", sa.Text(), nullable=True),
        sa.Column("tcmr_related_services", sa.JSON(), nullable=True),
        sa.Column("services", sa.JSON(), nullable=True),
        sa.Column("tcmr_planned_start_date", sa.DateTime(), nullable=True),
        sa.Column("tcmr_planned_end_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issue_key", name="uq_jira_issue_key"),
    )
    op.create_index(
        op.f("ix_jira_issues_created_at"), "jira_issues", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_jira_issues_issue_key"), "jira_issues", ["issue_key"], unique=False
    )
    op.create_index(
        op.f("ix_jira_issues_status_name"), "jira_issues", ["status_name"], unique=False
    )
    op.create_index(
        op.f("ix_jira_issues_ticket_type"), "jira_issues", ["ticket_type"], unique=False
    )
    op.create_table(
        "reliability_correlation_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("anchor_entity_id", sa.String(length=255), nullable=False),
        sa.Column("anchor_type", sa.String(length=255), nullable=False),
        sa.Column("services", mysql.JSON(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("correlation_timestamp", sa.DateTime(), nullable=False),
        sa.Column("base_score", sa.Float(), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("scoring_version", sa.String(length=255), nullable=True),
        sa.Column("feedback_list", mysql.JSON(), nullable=True),
        sa.Column(
            "feedback_state",
            sa.String(length=50),
            nullable=False,
            server_default="NEUTRAL",
        ),
        sa.Column("review_status", sa.Boolean(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anchor_entity_id",
            name="uq_reliability_correlation_groups_anchor_entity",
        ),
    )
    op.create_table(
        "reliability_correlations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("anchor_entity_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_type", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("services", mysql.JSON(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("base_score", sa.Float(), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("scoring_version", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anchor_entity_id",
            "entity_id",
            "correlation_type",
            name="uq_reliability_correlations_anchor_entity",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Idempotent teardown: drop with IF EXISTS so `downgrade base` (run during
    # pipeline resets) succeeds even when the target DB is in a partial state.
    # DROP TABLE removes a table's indexes implicitly, so explicit drop_index
    # calls are unnecessary. No FK constraints exist between these tables, so
    # drop order is unconstrained.
    for table in (
        "reliability_correlations",
        "reliability_correlation_groups",
        "jira_issues",
        "jira_batch_tracker",
        "incidentio_tracker",
        "incidentio_incidents",
        "greenroom_entities",
        "ghe_repositories",
        "ghe_pull_requests",
        "ghe_pr_tracker",
        "ghe_organizations",
    ):
        op.execute(f"DROP TABLE IF EXISTS `{table}`")
